-   id: laravel-pint
    name: Laravel Pint
    description: Run Laravel Pint code formatter
    entry: pint_hook.py
    language: python
    files: \.php$
    require_serial: true
    fail_fast: true