-   id: laravel-pint
    name: Laravel Pint
    description: Run Laravel Pint code formatter
    entry: bash -c 'vendor/bin/pint || (echo "Laravel Pint not found. Run composer install first." && exit 1)'
    language: system
    files: \.php$
    require_serial: true
    fail_fast: true