-   id: laravel-pint
    name: Laravel Pint
    description: Run Laravel Pint code formatter
    entry: bash -c 'vendor/bin/pint && git add -u'
    language: system
    files: \.php$
    require_serial: true
    fail_fast: true
    pass_filenames: false